//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuanTu.FuYangRMYY.HisOpBillAutoPayService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay", ConfigurationName="HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap")]
    public interface DHCOPBillAutoPaySOAPSoap {
        
        // CODEGEN: 命名空间 http://www.dhcc.com.cn/DHC/OPBILL/AutoPay 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay/web.DHCOPBillAutoPaySOAP.AutoOPBillChar" +
            "ge", ReplyAction="*")]
        YuanTu.FuYangRMYY.HisOpBillAutoPayService.AutoOPBillChargeResponse AutoOPBillCharge(YuanTu.FuYangRMYY.HisOpBillAutoPayService.AutoOPBillChargeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay/web.DHCOPBillAutoPaySOAP.AutoOPBillChar" +
            "ge", ReplyAction="*")]
        System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.AutoOPBillChargeResponse> AutoOPBillChargeAsync(YuanTu.FuYangRMYY.HisOpBillAutoPayService.AutoOPBillChargeRequest request);
        
        // CODEGEN: 命名空间 http://www.dhcc.com.cn/DHC/OPBILL/AutoPay 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay/web.DHCOPBillAutoPaySOAP.GetAdmByCardNo" +
            "", ReplyAction="*")]
        YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoResponse GetAdmByCardNo(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay/web.DHCOPBillAutoPaySOAP.GetAdmByCardNo" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoResponse> GetAdmByCardNoAsync(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoRequest request);
        
        // CODEGEN: 命名空间 http://www.dhcc.com.cn/DHC/OPBILL/AutoPay 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay/web.DHCOPBillAutoPaySOAP.GetAdmByCardNo" +
            "H", ReplyAction="*")]
        YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoHResponse GetAdmByCardNoH(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoHRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay/web.DHCOPBillAutoPaySOAP.GetAdmByCardNo" +
            "H", ReplyAction="*")]
        System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoHResponse> GetAdmByCardNoHAsync(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoHRequest request);
        
        // CODEGEN: 命名空间 http://www.dhcc.com.cn/DHC/OPBILL/AutoPay 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay/web.DHCOPBillAutoPaySOAP.GetBillDetailB" +
            "yAdm", ReplyAction="*")]
        YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillDetailByAdmResponse GetBillDetailByAdm(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillDetailByAdmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay/web.DHCOPBillAutoPaySOAP.GetBillDetailB" +
            "yAdm", ReplyAction="*")]
        System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillDetailByAdmResponse> GetBillDetailByAdmAsync(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillDetailByAdmRequest request);
        
        // CODEGEN: 命名空间 http://www.dhcc.com.cn/DHC/OPBILL/AutoPay 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay/web.DHCOPBillAutoPaySOAP.GetBillInfo", ReplyAction="*")]
        YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoResponse GetBillInfo(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay/web.DHCOPBillAutoPaySOAP.GetBillInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoResponse> GetBillInfoAsync(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoRequest request);
        
        // CODEGEN: 命名空间 http://www.dhcc.com.cn/DHC/OPBILL/AutoPay 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay/web.DHCOPBillAutoPaySOAP.GetBillInfoH", ReplyAction="*")]
        YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoHResponse GetBillInfoH(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoHRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay/web.DHCOPBillAutoPaySOAP.GetBillInfoH", ReplyAction="*")]
        System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoHResponse> GetBillInfoHAsync(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoHRequest request);
        
        // CODEGEN: 命名空间 http://www.dhcc.com.cn/DHC/OPBILL/AutoPay 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay/web.DHCOPBillAutoPaySOAP.GetPatientInfo" +
            "", ReplyAction="*")]
        YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetPatientInfoResponse GetPatientInfo(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetPatientInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay/web.DHCOPBillAutoPaySOAP.GetPatientInfo" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetPatientInfoResponse> GetPatientInfoAsync(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetPatientInfoRequest request);
        
        // CODEGEN: 命名空间 http://www.dhcc.com.cn/DHC/OPBILL/AutoPay 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay/web.DHCOPBillAutoPaySOAP.InsertBankTrad" +
            "eInfo", ReplyAction="*")]
        YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoResponse InsertBankTradeInfo(YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay/web.DHCOPBillAutoPaySOAP.InsertBankTrad" +
            "eInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoResponse> InsertBankTradeInfoAsync(YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoRequest request);
        
        // CODEGEN: 命名空间 http://www.dhcc.com.cn/DHC/OPBILL/AutoPay 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay/web.DHCOPBillAutoPaySOAP.InsertBankTrad" +
            "eInfoS", ReplyAction="*")]
        YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoSResponse InsertBankTradeInfoS(YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay/web.DHCOPBillAutoPaySOAP.InsertBankTrad" +
            "eInfoS", ReplyAction="*")]
        System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoSResponse> InsertBankTradeInfoSAsync(YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoSRequest request);
        
        // CODEGEN: 命名空间 http://www.dhcc.com.cn/DHC/OPBILL/AutoPay 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay/web.DHCOPBillAutoPaySOAP.OPAutoDailyFoo" +
            "t", ReplyAction="*")]
        YuanTu.FuYangRMYY.HisOpBillAutoPayService.OPAutoDailyFootResponse OPAutoDailyFoot(YuanTu.FuYangRMYY.HisOpBillAutoPayService.OPAutoDailyFootRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay/web.DHCOPBillAutoPaySOAP.OPAutoDailyFoo" +
            "t", ReplyAction="*")]
        System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.OPAutoDailyFootResponse> OPAutoDailyFootAsync(YuanTu.FuYangRMYY.HisOpBillAutoPayService.OPAutoDailyFootRequest request);
        
        // CODEGEN: 命名空间 http://www.dhcc.com.cn/DHC/OPBILL/AutoPay 的元素名称 TestStreamResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay/web.DHCOPBillAutoPaySOAP.TestStream", ReplyAction="*")]
        YuanTu.FuYangRMYY.HisOpBillAutoPayService.TestStreamResponse TestStream(YuanTu.FuYangRMYY.HisOpBillAutoPayService.TestStreamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay/web.DHCOPBillAutoPaySOAP.TestStream", ReplyAction="*")]
        System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.TestStreamResponse> TestStreamAsync(YuanTu.FuYangRMYY.HisOpBillAutoPayService.TestStreamRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoOPBillChargeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoOPBillCharge", Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay", Order=0)]
        public YuanTu.FuYangRMYY.HisOpBillAutoPayService.AutoOPBillChargeRequestBody Body;
        
        public AutoOPBillChargeRequest() {
        }
        
        public AutoOPBillChargeRequest(YuanTu.FuYangRMYY.HisOpBillAutoPayService.AutoOPBillChargeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay")]
    public partial class AutoOPBillChargeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public AutoOPBillChargeRequestBody() {
        }
        
        public AutoOPBillChargeRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoOPBillChargeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoOPBillChargeResponse", Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay", Order=0)]
        public YuanTu.FuYangRMYY.HisOpBillAutoPayService.AutoOPBillChargeResponseBody Body;
        
        public AutoOPBillChargeResponse() {
        }
        
        public AutoOPBillChargeResponse(YuanTu.FuYangRMYY.HisOpBillAutoPayService.AutoOPBillChargeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay")]
    public partial class AutoOPBillChargeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AutoOPBillChargeResult;
        
        public AutoOPBillChargeResponseBody() {
        }
        
        public AutoOPBillChargeResponseBody(string AutoOPBillChargeResult) {
            this.AutoOPBillChargeResult = AutoOPBillChargeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAdmByCardNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAdmByCardNo", Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay", Order=0)]
        public YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoRequestBody Body;
        
        public GetAdmByCardNoRequest() {
        }
        
        public GetAdmByCardNoRequest(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay")]
    public partial class GetAdmByCardNoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public GetAdmByCardNoRequestBody() {
        }
        
        public GetAdmByCardNoRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAdmByCardNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAdmByCardNoResponse", Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay", Order=0)]
        public YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoResponseBody Body;
        
        public GetAdmByCardNoResponse() {
        }
        
        public GetAdmByCardNoResponse(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay")]
    public partial class GetAdmByCardNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAdmByCardNoResult;
        
        public GetAdmByCardNoResponseBody() {
        }
        
        public GetAdmByCardNoResponseBody(string GetAdmByCardNoResult) {
            this.GetAdmByCardNoResult = GetAdmByCardNoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAdmByCardNoHRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAdmByCardNoH", Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay", Order=0)]
        public YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoHRequestBody Body;
        
        public GetAdmByCardNoHRequest() {
        }
        
        public GetAdmByCardNoHRequest(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoHRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay")]
    public partial class GetAdmByCardNoHRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public GetAdmByCardNoHRequestBody() {
        }
        
        public GetAdmByCardNoHRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAdmByCardNoHResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAdmByCardNoHResponse", Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay", Order=0)]
        public YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoHResponseBody Body;
        
        public GetAdmByCardNoHResponse() {
        }
        
        public GetAdmByCardNoHResponse(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoHResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay")]
    public partial class GetAdmByCardNoHResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAdmByCardNoHResult;
        
        public GetAdmByCardNoHResponseBody() {
        }
        
        public GetAdmByCardNoHResponseBody(string GetAdmByCardNoHResult) {
            this.GetAdmByCardNoHResult = GetAdmByCardNoHResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBillDetailByAdmRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBillDetailByAdm", Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay", Order=0)]
        public YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillDetailByAdmRequestBody Body;
        
        public GetBillDetailByAdmRequest() {
        }
        
        public GetBillDetailByAdmRequest(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillDetailByAdmRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay")]
    public partial class GetBillDetailByAdmRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public GetBillDetailByAdmRequestBody() {
        }
        
        public GetBillDetailByAdmRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBillDetailByAdmResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBillDetailByAdmResponse", Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay", Order=0)]
        public YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillDetailByAdmResponseBody Body;
        
        public GetBillDetailByAdmResponse() {
        }
        
        public GetBillDetailByAdmResponse(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillDetailByAdmResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay")]
    public partial class GetBillDetailByAdmResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBillDetailByAdmResult;
        
        public GetBillDetailByAdmResponseBody() {
        }
        
        public GetBillDetailByAdmResponseBody(string GetBillDetailByAdmResult) {
            this.GetBillDetailByAdmResult = GetBillDetailByAdmResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBillInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBillInfo", Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay", Order=0)]
        public YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoRequestBody Body;
        
        public GetBillInfoRequest() {
        }
        
        public GetBillInfoRequest(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay")]
    public partial class GetBillInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public GetBillInfoRequestBody() {
        }
        
        public GetBillInfoRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBillInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBillInfoResponse", Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay", Order=0)]
        public YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoResponseBody Body;
        
        public GetBillInfoResponse() {
        }
        
        public GetBillInfoResponse(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay")]
    public partial class GetBillInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBillInfoResult;
        
        public GetBillInfoResponseBody() {
        }
        
        public GetBillInfoResponseBody(string GetBillInfoResult) {
            this.GetBillInfoResult = GetBillInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBillInfoHRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBillInfoH", Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay", Order=0)]
        public YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoHRequestBody Body;
        
        public GetBillInfoHRequest() {
        }
        
        public GetBillInfoHRequest(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoHRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay")]
    public partial class GetBillInfoHRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public GetBillInfoHRequestBody() {
        }
        
        public GetBillInfoHRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBillInfoHResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBillInfoHResponse", Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay", Order=0)]
        public YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoHResponseBody Body;
        
        public GetBillInfoHResponse() {
        }
        
        public GetBillInfoHResponse(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoHResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay")]
    public partial class GetBillInfoHResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBillInfoHResult;
        
        public GetBillInfoHResponseBody() {
        }
        
        public GetBillInfoHResponseBody(string GetBillInfoHResult) {
            this.GetBillInfoHResult = GetBillInfoHResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPatientInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPatientInfo", Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay", Order=0)]
        public YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetPatientInfoRequestBody Body;
        
        public GetPatientInfoRequest() {
        }
        
        public GetPatientInfoRequest(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetPatientInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay")]
    public partial class GetPatientInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public GetPatientInfoRequestBody() {
        }
        
        public GetPatientInfoRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPatientInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPatientInfoResponse", Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay", Order=0)]
        public YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetPatientInfoResponseBody Body;
        
        public GetPatientInfoResponse() {
        }
        
        public GetPatientInfoResponse(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetPatientInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay")]
    public partial class GetPatientInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPatientInfoResult;
        
        public GetPatientInfoResponseBody() {
        }
        
        public GetPatientInfoResponseBody(string GetPatientInfoResult) {
            this.GetPatientInfoResult = GetPatientInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertBankTradeInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertBankTradeInfo", Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay", Order=0)]
        public YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoRequestBody Body;
        
        public InsertBankTradeInfoRequest() {
        }
        
        public InsertBankTradeInfoRequest(YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay")]
    public partial class InsertBankTradeInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public InsertBankTradeInfoRequestBody() {
        }
        
        public InsertBankTradeInfoRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertBankTradeInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertBankTradeInfoResponse", Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay", Order=0)]
        public YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoResponseBody Body;
        
        public InsertBankTradeInfoResponse() {
        }
        
        public InsertBankTradeInfoResponse(YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay")]
    public partial class InsertBankTradeInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertBankTradeInfoResult;
        
        public InsertBankTradeInfoResponseBody() {
        }
        
        public InsertBankTradeInfoResponseBody(string InsertBankTradeInfoResult) {
            this.InsertBankTradeInfoResult = InsertBankTradeInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertBankTradeInfoSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertBankTradeInfoS", Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay", Order=0)]
        public YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoSRequestBody Body;
        
        public InsertBankTradeInfoSRequest() {
        }
        
        public InsertBankTradeInfoSRequest(YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay")]
    public partial class InsertBankTradeInfoSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public InsertBankTradeInfoSRequestBody() {
        }
        
        public InsertBankTradeInfoSRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertBankTradeInfoSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertBankTradeInfoSResponse", Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay", Order=0)]
        public YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoSResponseBody Body;
        
        public InsertBankTradeInfoSResponse() {
        }
        
        public InsertBankTradeInfoSResponse(YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay")]
    public partial class InsertBankTradeInfoSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertBankTradeInfoSResult;
        
        public InsertBankTradeInfoSResponseBody() {
        }
        
        public InsertBankTradeInfoSResponseBody(string InsertBankTradeInfoSResult) {
            this.InsertBankTradeInfoSResult = InsertBankTradeInfoSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OPAutoDailyFootRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OPAutoDailyFoot", Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay", Order=0)]
        public YuanTu.FuYangRMYY.HisOpBillAutoPayService.OPAutoDailyFootRequestBody Body;
        
        public OPAutoDailyFootRequest() {
        }
        
        public OPAutoDailyFootRequest(YuanTu.FuYangRMYY.HisOpBillAutoPayService.OPAutoDailyFootRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay")]
    public partial class OPAutoDailyFootRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public OPAutoDailyFootRequestBody() {
        }
        
        public OPAutoDailyFootRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OPAutoDailyFootResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OPAutoDailyFootResponse", Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay", Order=0)]
        public YuanTu.FuYangRMYY.HisOpBillAutoPayService.OPAutoDailyFootResponseBody Body;
        
        public OPAutoDailyFootResponse() {
        }
        
        public OPAutoDailyFootResponse(YuanTu.FuYangRMYY.HisOpBillAutoPayService.OPAutoDailyFootResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay")]
    public partial class OPAutoDailyFootResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OPAutoDailyFootResult;
        
        public OPAutoDailyFootResponseBody() {
        }
        
        public OPAutoDailyFootResponseBody(string OPAutoDailyFootResult) {
            this.OPAutoDailyFootResult = OPAutoDailyFootResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestStreamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestStream", Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay", Order=0)]
        public YuanTu.FuYangRMYY.HisOpBillAutoPayService.TestStreamRequestBody Body;
        
        public TestStreamRequest() {
        }
        
        public TestStreamRequest(YuanTu.FuYangRMYY.HisOpBillAutoPayService.TestStreamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestStreamRequestBody {
        
        public TestStreamRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestStreamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestStreamResponse", Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay", Order=0)]
        public YuanTu.FuYangRMYY.HisOpBillAutoPayService.TestStreamResponseBody Body;
        
        public TestStreamResponse() {
        }
        
        public TestStreamResponse(YuanTu.FuYangRMYY.HisOpBillAutoPayService.TestStreamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dhcc.com.cn/DHC/OPBILL/AutoPay")]
    public partial class TestStreamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestStreamResult;
        
        public TestStreamResponseBody() {
        }
        
        public TestStreamResponseBody(string TestStreamResult) {
            this.TestStreamResult = TestStreamResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DHCOPBillAutoPaySOAPSoapChannel : YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DHCOPBillAutoPaySOAPSoapClient : System.ServiceModel.ClientBase<YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap>, YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap {
        
        public DHCOPBillAutoPaySOAPSoapClient() {
        }
        
        public DHCOPBillAutoPaySOAPSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DHCOPBillAutoPaySOAPSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DHCOPBillAutoPaySOAPSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DHCOPBillAutoPaySOAPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YuanTu.FuYangRMYY.HisOpBillAutoPayService.AutoOPBillChargeResponse YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap.AutoOPBillCharge(YuanTu.FuYangRMYY.HisOpBillAutoPayService.AutoOPBillChargeRequest request) {
            return base.Channel.AutoOPBillCharge(request);
        }
        
        public string AutoOPBillCharge(string input) {
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.AutoOPBillChargeRequest inValue = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.AutoOPBillChargeRequest();
            inValue.Body = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.AutoOPBillChargeRequestBody();
            inValue.Body.input = input;
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.AutoOPBillChargeResponse retVal = ((YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap)(this)).AutoOPBillCharge(inValue);
            return retVal.Body.AutoOPBillChargeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.AutoOPBillChargeResponse> YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap.AutoOPBillChargeAsync(YuanTu.FuYangRMYY.HisOpBillAutoPayService.AutoOPBillChargeRequest request) {
            return base.Channel.AutoOPBillChargeAsync(request);
        }
        
        public System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.AutoOPBillChargeResponse> AutoOPBillChargeAsync(string input) {
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.AutoOPBillChargeRequest inValue = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.AutoOPBillChargeRequest();
            inValue.Body = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.AutoOPBillChargeRequestBody();
            inValue.Body.input = input;
            return ((YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap)(this)).AutoOPBillChargeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoResponse YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap.GetAdmByCardNo(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoRequest request) {
            return base.Channel.GetAdmByCardNo(request);
        }
        
        public string GetAdmByCardNo(string input) {
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoRequest inValue = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoRequest();
            inValue.Body = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoRequestBody();
            inValue.Body.input = input;
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoResponse retVal = ((YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap)(this)).GetAdmByCardNo(inValue);
            return retVal.Body.GetAdmByCardNoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoResponse> YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap.GetAdmByCardNoAsync(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoRequest request) {
            return base.Channel.GetAdmByCardNoAsync(request);
        }
        
        public System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoResponse> GetAdmByCardNoAsync(string input) {
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoRequest inValue = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoRequest();
            inValue.Body = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoRequestBody();
            inValue.Body.input = input;
            return ((YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap)(this)).GetAdmByCardNoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoHResponse YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap.GetAdmByCardNoH(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoHRequest request) {
            return base.Channel.GetAdmByCardNoH(request);
        }
        
        public string GetAdmByCardNoH(string input) {
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoHRequest inValue = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoHRequest();
            inValue.Body = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoHRequestBody();
            inValue.Body.input = input;
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoHResponse retVal = ((YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap)(this)).GetAdmByCardNoH(inValue);
            return retVal.Body.GetAdmByCardNoHResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoHResponse> YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap.GetAdmByCardNoHAsync(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoHRequest request) {
            return base.Channel.GetAdmByCardNoHAsync(request);
        }
        
        public System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoHResponse> GetAdmByCardNoHAsync(string input) {
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoHRequest inValue = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoHRequest();
            inValue.Body = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetAdmByCardNoHRequestBody();
            inValue.Body.input = input;
            return ((YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap)(this)).GetAdmByCardNoHAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillDetailByAdmResponse YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap.GetBillDetailByAdm(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillDetailByAdmRequest request) {
            return base.Channel.GetBillDetailByAdm(request);
        }
        
        public string GetBillDetailByAdm(string input) {
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillDetailByAdmRequest inValue = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillDetailByAdmRequest();
            inValue.Body = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillDetailByAdmRequestBody();
            inValue.Body.input = input;
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillDetailByAdmResponse retVal = ((YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap)(this)).GetBillDetailByAdm(inValue);
            return retVal.Body.GetBillDetailByAdmResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillDetailByAdmResponse> YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap.GetBillDetailByAdmAsync(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillDetailByAdmRequest request) {
            return base.Channel.GetBillDetailByAdmAsync(request);
        }
        
        public System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillDetailByAdmResponse> GetBillDetailByAdmAsync(string input) {
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillDetailByAdmRequest inValue = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillDetailByAdmRequest();
            inValue.Body = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillDetailByAdmRequestBody();
            inValue.Body.input = input;
            return ((YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap)(this)).GetBillDetailByAdmAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoResponse YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap.GetBillInfo(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoRequest request) {
            return base.Channel.GetBillInfo(request);
        }
        
        public string GetBillInfo(string input) {
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoRequest inValue = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoRequest();
            inValue.Body = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoRequestBody();
            inValue.Body.input = input;
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoResponse retVal = ((YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap)(this)).GetBillInfo(inValue);
            return retVal.Body.GetBillInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoResponse> YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap.GetBillInfoAsync(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoRequest request) {
            return base.Channel.GetBillInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoResponse> GetBillInfoAsync(string input) {
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoRequest inValue = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoRequest();
            inValue.Body = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoRequestBody();
            inValue.Body.input = input;
            return ((YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap)(this)).GetBillInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoHResponse YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap.GetBillInfoH(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoHRequest request) {
            return base.Channel.GetBillInfoH(request);
        }
        
        public string GetBillInfoH(string input) {
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoHRequest inValue = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoHRequest();
            inValue.Body = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoHRequestBody();
            inValue.Body.input = input;
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoHResponse retVal = ((YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap)(this)).GetBillInfoH(inValue);
            return retVal.Body.GetBillInfoHResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoHResponse> YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap.GetBillInfoHAsync(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoHRequest request) {
            return base.Channel.GetBillInfoHAsync(request);
        }
        
        public System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoHResponse> GetBillInfoHAsync(string input) {
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoHRequest inValue = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoHRequest();
            inValue.Body = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetBillInfoHRequestBody();
            inValue.Body.input = input;
            return ((YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap)(this)).GetBillInfoHAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetPatientInfoResponse YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap.GetPatientInfo(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetPatientInfoRequest request) {
            return base.Channel.GetPatientInfo(request);
        }
        
        public string GetPatientInfo(string input) {
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetPatientInfoRequest inValue = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetPatientInfoRequest();
            inValue.Body = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetPatientInfoRequestBody();
            inValue.Body.input = input;
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetPatientInfoResponse retVal = ((YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap)(this)).GetPatientInfo(inValue);
            return retVal.Body.GetPatientInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetPatientInfoResponse> YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap.GetPatientInfoAsync(YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetPatientInfoRequest request) {
            return base.Channel.GetPatientInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetPatientInfoResponse> GetPatientInfoAsync(string input) {
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetPatientInfoRequest inValue = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetPatientInfoRequest();
            inValue.Body = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.GetPatientInfoRequestBody();
            inValue.Body.input = input;
            return ((YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap)(this)).GetPatientInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoResponse YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap.InsertBankTradeInfo(YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoRequest request) {
            return base.Channel.InsertBankTradeInfo(request);
        }
        
        public string InsertBankTradeInfo(string input) {
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoRequest inValue = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoRequest();
            inValue.Body = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoRequestBody();
            inValue.Body.input = input;
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoResponse retVal = ((YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap)(this)).InsertBankTradeInfo(inValue);
            return retVal.Body.InsertBankTradeInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoResponse> YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap.InsertBankTradeInfoAsync(YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoRequest request) {
            return base.Channel.InsertBankTradeInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoResponse> InsertBankTradeInfoAsync(string input) {
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoRequest inValue = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoRequest();
            inValue.Body = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoRequestBody();
            inValue.Body.input = input;
            return ((YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap)(this)).InsertBankTradeInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoSResponse YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap.InsertBankTradeInfoS(YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoSRequest request) {
            return base.Channel.InsertBankTradeInfoS(request);
        }
        
        public string InsertBankTradeInfoS(string input) {
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoSRequest inValue = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoSRequest();
            inValue.Body = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoSRequestBody();
            inValue.Body.input = input;
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoSResponse retVal = ((YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap)(this)).InsertBankTradeInfoS(inValue);
            return retVal.Body.InsertBankTradeInfoSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoSResponse> YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap.InsertBankTradeInfoSAsync(YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoSRequest request) {
            return base.Channel.InsertBankTradeInfoSAsync(request);
        }
        
        public System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoSResponse> InsertBankTradeInfoSAsync(string input) {
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoSRequest inValue = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoSRequest();
            inValue.Body = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.InsertBankTradeInfoSRequestBody();
            inValue.Body.input = input;
            return ((YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap)(this)).InsertBankTradeInfoSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YuanTu.FuYangRMYY.HisOpBillAutoPayService.OPAutoDailyFootResponse YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap.OPAutoDailyFoot(YuanTu.FuYangRMYY.HisOpBillAutoPayService.OPAutoDailyFootRequest request) {
            return base.Channel.OPAutoDailyFoot(request);
        }
        
        public string OPAutoDailyFoot(string input) {
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.OPAutoDailyFootRequest inValue = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.OPAutoDailyFootRequest();
            inValue.Body = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.OPAutoDailyFootRequestBody();
            inValue.Body.input = input;
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.OPAutoDailyFootResponse retVal = ((YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap)(this)).OPAutoDailyFoot(inValue);
            return retVal.Body.OPAutoDailyFootResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.OPAutoDailyFootResponse> YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap.OPAutoDailyFootAsync(YuanTu.FuYangRMYY.HisOpBillAutoPayService.OPAutoDailyFootRequest request) {
            return base.Channel.OPAutoDailyFootAsync(request);
        }
        
        public System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.OPAutoDailyFootResponse> OPAutoDailyFootAsync(string input) {
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.OPAutoDailyFootRequest inValue = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.OPAutoDailyFootRequest();
            inValue.Body = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.OPAutoDailyFootRequestBody();
            inValue.Body.input = input;
            return ((YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap)(this)).OPAutoDailyFootAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YuanTu.FuYangRMYY.HisOpBillAutoPayService.TestStreamResponse YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap.TestStream(YuanTu.FuYangRMYY.HisOpBillAutoPayService.TestStreamRequest request) {
            return base.Channel.TestStream(request);
        }
        
        public string TestStream() {
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.TestStreamRequest inValue = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.TestStreamRequest();
            inValue.Body = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.TestStreamRequestBody();
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.TestStreamResponse retVal = ((YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap)(this)).TestStream(inValue);
            return retVal.Body.TestStreamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.TestStreamResponse> YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap.TestStreamAsync(YuanTu.FuYangRMYY.HisOpBillAutoPayService.TestStreamRequest request) {
            return base.Channel.TestStreamAsync(request);
        }
        
        public System.Threading.Tasks.Task<YuanTu.FuYangRMYY.HisOpBillAutoPayService.TestStreamResponse> TestStreamAsync() {
            YuanTu.FuYangRMYY.HisOpBillAutoPayService.TestStreamRequest inValue = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.TestStreamRequest();
            inValue.Body = new YuanTu.FuYangRMYY.HisOpBillAutoPayService.TestStreamRequestBody();
            return ((YuanTu.FuYangRMYY.HisOpBillAutoPayService.DHCOPBillAutoPaySOAPSoap)(this)).TestStreamAsync(inValue);
        }
    }
}
