//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuanTu.ZheJiangHospital.Appoint {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="open", ConfigurationName="Appoint.openSoap")]
    public interface openSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="open/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="open/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="open/HelloWorld2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld2(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="open/HelloWorld2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorld2Async(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="open/funMain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string funMain(string xmldoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="open/funMain", ReplyAction="*")]
        System.Threading.Tasks.Task<string> funMainAsync(string xmldoc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface openSoapChannel : YuanTu.ZheJiangHospital.Appoint.openSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class openSoapClient : System.ServiceModel.ClientBase<YuanTu.ZheJiangHospital.Appoint.openSoap>, YuanTu.ZheJiangHospital.Appoint.openSoap {
        
        public openSoapClient() {
        }
        
        public openSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public openSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public openSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public openSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string HelloWorld2(string Name) {
            return base.Channel.HelloWorld2(Name);
        }
        
        public System.Threading.Tasks.Task<string> HelloWorld2Async(string Name) {
            return base.Channel.HelloWorld2Async(Name);
        }
        
        public string funMain(string xmldoc) {
            return base.Channel.funMain(xmldoc);
        }
        
        public System.Threading.Tasks.Task<string> funMainAsync(string xmldoc) {
            return base.Channel.funMainAsync(xmldoc);
        }
    }
}
