//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuanTu.XiaoShanZYY.HIS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempurl.org", ConfigurationName="HIS.hissvrSoap")]
    public interface hissvrSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempurl.org/runservice", ReplyAction="*")]
        YuanTu.XiaoShanZYY.HIS.runserviceResponse runservice(YuanTu.XiaoShanZYY.HIS.runserviceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempurl.org/runservice", ReplyAction="*")]
        System.Threading.Tasks.Task<YuanTu.XiaoShanZYY.HIS.runserviceResponse> runserviceAsync(YuanTu.XiaoShanZYY.HIS.runserviceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class runserviceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="runservice", Namespace="http://tempurl.org", Order=0)]
        public YuanTu.XiaoShanZYY.HIS.runserviceRequestBody Body;
        
        public runserviceRequest() {
        }
        
        public runserviceRequest(YuanTu.XiaoShanZYY.HIS.runserviceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempurl.org")]
    public partial class runserviceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tradetype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string trademsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tradeout;
        
        public runserviceRequestBody() {
        }
        
        public runserviceRequestBody(string tradetype, string trademsg, string tradeout) {
            this.tradetype = tradetype;
            this.trademsg = trademsg;
            this.tradeout = tradeout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class runserviceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="runserviceResponse", Namespace="http://tempurl.org", Order=0)]
        public YuanTu.XiaoShanZYY.HIS.runserviceResponseBody Body;
        
        public runserviceResponse() {
        }
        
        public runserviceResponse(YuanTu.XiaoShanZYY.HIS.runserviceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempurl.org")]
    public partial class runserviceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public short runserviceResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tradeout;
        
        public runserviceResponseBody() {
        }
        
        public runserviceResponseBody(short runserviceResult, string tradeout) {
            this.runserviceResult = runserviceResult;
            this.tradeout = tradeout;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface hissvrSoapChannel : YuanTu.XiaoShanZYY.HIS.hissvrSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class hissvrSoapClient : System.ServiceModel.ClientBase<YuanTu.XiaoShanZYY.HIS.hissvrSoap>, YuanTu.XiaoShanZYY.HIS.hissvrSoap {
        
        public hissvrSoapClient() {
        }
        
        public hissvrSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public hissvrSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public hissvrSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public hissvrSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YuanTu.XiaoShanZYY.HIS.runserviceResponse YuanTu.XiaoShanZYY.HIS.hissvrSoap.runservice(YuanTu.XiaoShanZYY.HIS.runserviceRequest request) {
            return base.Channel.runservice(request);
        }
        
        public short runservice(string tradetype, string trademsg, ref string tradeout) {
            YuanTu.XiaoShanZYY.HIS.runserviceRequest inValue = new YuanTu.XiaoShanZYY.HIS.runserviceRequest();
            inValue.Body = new YuanTu.XiaoShanZYY.HIS.runserviceRequestBody();
            inValue.Body.tradetype = tradetype;
            inValue.Body.trademsg = trademsg;
            inValue.Body.tradeout = tradeout;
            YuanTu.XiaoShanZYY.HIS.runserviceResponse retVal = ((YuanTu.XiaoShanZYY.HIS.hissvrSoap)(this)).runservice(inValue);
            tradeout = retVal.Body.tradeout;
            return retVal.Body.runserviceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YuanTu.XiaoShanZYY.HIS.runserviceResponse> YuanTu.XiaoShanZYY.HIS.hissvrSoap.runserviceAsync(YuanTu.XiaoShanZYY.HIS.runserviceRequest request) {
            return base.Channel.runserviceAsync(request);
        }
        
        public System.Threading.Tasks.Task<YuanTu.XiaoShanZYY.HIS.runserviceResponse> runserviceAsync(string tradetype, string trademsg, string tradeout) {
            YuanTu.XiaoShanZYY.HIS.runserviceRequest inValue = new YuanTu.XiaoShanZYY.HIS.runserviceRequest();
            inValue.Body = new YuanTu.XiaoShanZYY.HIS.runserviceRequestBody();
            inValue.Body.tradetype = tradetype;
            inValue.Body.trademsg = trademsg;
            inValue.Body.tradeout = tradeout;
            return ((YuanTu.XiaoShanZYY.HIS.hissvrSoap)(this)).runserviceAsync(inValue);
        }
    }
}
